### ISSUE TITLE
Create `Makefile`

### ISSUE THREAD

**Issue by kiprasmel** [sarpik/git-backup#1]
### Task

Create a `Makefile` that would

* [x] install the script in the appropriate `/usr` location - 7b2a6f016af6c83c5c5fb194291b4eb325b4e0d9
	* [x] re-search the proper `/usr` location
* [x] Update README - 3021bef7480857335ba7e9c0cd1029b06516ed4c
* [x] install ~~& gzip~~ the manual page (*git-backup*(1)) (why gzip?)

### Notes

probably use `install` & `gzip` utils.

~~maaaaybe consider windows?~~ lmao normies

High priority, since the user has to manually add the script to his path or the appropriate `/usr` location.

Same with the manual page. And the `-m` option won't work since the manual page is not provided.
