### ISSUE TITLE
Create `restore from backup` functionality

### ISSUE THREAD

**Issue by kiprasmel** [sarpik/git-backup#4]
### Task

* [ ] Create a function which would restore changes from
	* [ ] XYZ backup
		* [ ] list backups - #6
			* [ ] select one to restore from

	* [ ] latest backup
		* [ ] Identify the latest backup (probably by the unix date timestamp we add to the branch name) (create as separate function since it'd be needed for other stuff too)

* [ ] implement an option to activate this function
	* [ ] think of a good name
	* [ ] handle in the script
	* [ ] update docs
		* [ ] raw
		* [ ] manual page

**Comment by kiprasmel** [comment]
`git stash apply`. Would be awesome being able to restore from a remote though.
