### ISSUE TITLE
Create `delete backup` functionality

### ISSUE THREAD

**Issue by kiprasmel** [sarpik/git-backup#5]
### Task

* [ ] Create a function which delete backups
	* [ ] Figure out how we want to display current backups so that we can
		* [ ] select *one* or *multiple* of them
	* [ ] One of them
	* [ ] Multiple
	* [ ] All
	* [ ] Make it work with remote backups (`git push origin :branch-name`)

**Comment by kiprasmel** [comment]
Imitate `git stash drop|clear`. Though we'd instead need to delete the branch remotely and locally, so `git branch -d` would be used instead.

It'd be great to be able to delete branches in bulk.
