### ISSUE TITLE
Create `list backups` functionality

### ISSUE THREAD

**Issue by kiprasmel** [sarpik/git-backup#6]
### Task

- [ ] Create a function which would list backups
	- [ ] Local backups
	- [ ] Remote backups
	- [ ] Both
	- [ ] Decide which backups should be listed by default

- [ ] Implement an option to activate this function
	- [ ] think of a good name
	- [ ] handle in the script
	- [ ] update docs
		- [ ] raw
		- [ ] manual page

- [ ] Make it extendable for other commands (see #4 & #5)
	- [ ] Make a single or multiple backups selectable (probably in interactive mode, something like `git rebase -i`)

### Future

* Display which ones can be backed up (to where `HEAD` points to, checking if the changes could apply without conflicts (check by commits/refs/whatever-works, if possible, to avoid having to test every backup))

**Comment by kiprasmel** [comment]
It might be worth considering to stay as close to `git stash` as possible, and thus doing something very similar to `git stash list` would be enough and great. We can add sugar later.
